TravelGo/Areas/Admin/Controllers/GuideController.cs
using BusinessLayer.Abstract;
using BusinessLayer.ValidationRules;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace TravelGo.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("[area]/[controller]/[action]")]
    public class GuideController : Controller
    {
        private readonly IGuideService _guideService;

        public GuideController(IGuideService guideService)
        {
            _guideService = guideService;
        }

        public IActionResult Index()
        {
            return View(_guideService.TGetList());
        }
        [HttpGet]
        public IActionResult AddGuide()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddGuide(Guide guide)
        {
            GuideValidator validationRules = new GuideValidator();
            var validate=validationRules.Validate(guide);
            if (validate.IsValid)
            {
                _guideService.TAdd(guide);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                foreach (var item in validate.Errors)
                {
                    ModelState.AddModelError(item.ErrorCode,item.ErrorMessage);
                }
                return View();
            }

        }
        [HttpGet]
        public IActionResult UpdateGuide(int id)
        {
            return View(_guideService.TGetById(id));
        }

        [HttpPost]
        public IActionResult UpdateGuide(Guide guide)
        {
            _guideService.TUpdate(guide);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult ChangeStatus(int id)
        {
            Guide guide = _guideService.TGetById(id);
            if (guide.Status == true)
            {
                guide.Status = false; 
            }
            else
            {
                guide.Status = true;
            }
            _guideService.TUpdate(guide);
            return RedirectToAction(nameof(Index));
        }
    }
}

TravelGo/Controllers/GuideController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TravelGo.Controllers
{
    [AllowAnonymous]
    public class GuideController : Controller
    {
        IGuideService _guideService;

        public GuideController(IGuideService guideService)
        {
            _guideService = guideService;
        }

        public IActionResult Index()
        {
            return View(_guideService.TGetList());
        }
    }
}

TravelGo/Areas/Admin/Views/Guide/AddGuide.cshtml
@using EntityLayer.Concrete;

@{
    ViewData["Title"] = "AddGuide";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@model Guide


<h1>NewReservation Page</h1>
<div asp-validation-summary="All" style="color:red;"></div>
<form method="post">

    <div class="form-group">
        <label for="PersonCount">Name</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label for="ReservationDate">Twitter Url</label>
        <input type="text" asp-for="TwitterUrl" class="form-control" />
    </div>
    <div class="form-group">
        <label for="ReservationDate">Instagram</label>
        <input type="text" asp-for="InstagramUrl" class="form-control">
    </div>
    <div class="form-group">
        <label for="ReservationDate">Image</label>
        <input type="text" asp-for="Image" class="form-control">
    </div>
    <div class="form-group">
        <label for="ReservationDate">Description</label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="ReservationDate">Status</label>
        <input type="text" asp-for="Status" class="form-control">
    </div>
 
    <button type="submit" class="btn btn-primary">Create</button>
</form>

TravelGo/Areas/Admin/Views/Guide/Index.cshtml
@using EntityLayer.Concrete;
@model List<Guide>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <h1>Guide List</h1>
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>UserName</th>
                <th>About</th>
                <th>Status</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.GuideId</td>
                    <td><img style="width:100px; border-radius:50%;" src="@item.Image" /></td>
                    <td>@item.Name</td>
                    <td>@item.Description</td>
                    <td>
                        @if (item.Status)
                        {
                            <a class="btn btn-success" style="color:white;" asp-action="ChangeStatus" asp-controller="Guide" asp-route-id="@item.GuideId" asp-area="Admin">Active</a>
                        }
                        @if (!item.Status)
                        {
                            <a class="btn btn-danger" style="color:white;" asp-action="ChangeStatus" asp-controller="Guide" asp-route-id="@item.GuideId" asp-area="Admin">Passive</a>

                        }
                        </td >
                    <td><a class="btn btn-primary" style="color:white;">Edit</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>


<div class="buy-now">
    <a asp-action="AddGuide" asp-controller="Guide" asp-area="admin"
       target="_blank"
       class="btn btn-success btn-buy-now">Add new Guide</a>
</div>